import test from 'node:test';
import assert from 'node:assert/strict';
import {httpsURL,calendarText,validateAttachment,makeClient} from '../src/data.ts';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
test('Meeting links cannot execute script or include credentials',()=>{for(const input of ['javascript:alert(1)','data:text/html,test','http://zoom.us','https://name:secret@zoom.us'])assert.equal(httpsURL(input),null);assert.equal(httpsURL('https://us06web.zoom.us/j/123?pwd=abc'),'https://us06web.zoom.us/j/123?pwd=abc');});
test('Paris meeting keeps its UTC instant and cannot inject calendar fields',()=>{const text=calendarText({id:1,title:'Reset\r\nATTENDEE:bad',kind:'live',description:'a,b;c',starts_at:'2026-10-11T19:00:00+02:00',duration_min:null,join_url:'https://zoom.us/j/123',replay_url:null});assert.match(text,/DTSTART:20261011T170000Z/);assert.ok(!text.includes('\r\nATTENDEE'));assert.ok(!text.includes('DTEND:'));assert.match(text,/a\\,b\\;c/);});
test('Attachments reject oversized or active documents before uploading',()=>{for(const file of [{name:'test.html',type:'text/html',size:10},{name:'large.png',type:'image/png',size:21*1024*1024},{name:'empty.pdf',type:'application/pdf',size:0}])assert.throws(()=>validateAttachment(file));validateAttachment({name:'practice.pdf',type:'application/pdf',size:1024});});
test('Service worker never intercepts member data or signed media',()=>{const listeners:Record<string,(event:any)=>void>={};vm.runInNewContext(readFileSync(new URL('../public/sw.js',import.meta.url),'utf8'),{URL,self:{location:{origin:'https://www.well-vie.com'},addEventListener:(name:string,fn:any)=>listeners[name]=fn},caches:{},fetch:()=>{throw Error('Private request intercepted');}});for(const url of ['https://www.well-vie.com/app/','https://www.well-vie.com/app/assets/file.js?token=secret','https://xsltodvgquimppfetmzv.supabase.co/storage/v1/object/sign/private/audio.mp3?token=secret','https://clerk.well-vie.com/v1/client','https://www.well-vie.com/privacy/']){let intercepted=false;listeners.fetch({request:{url,method:'GET'},respondWith:()=>{intercepted=true}});assert.equal(intercepted,false,url);}});
