import {useEffect,useRef,useState} from 'react';
import {BookOpen,Download,History,PenLine,Trash2,Quote} from 'lucide-react';
import {useMember} from './context';
import {type Entry,type Intention,type Checkin,result,rpc,allRows,downloadText,cleanCopy} from './data';
import {Page,Loading,ErrorBox,Empty,useLoad,useAction,dateLabel,timeLabel} from './ui';
const journalColumns='id,title,prompt_text,practice_id,body,created_at';
export function Journal(){
  const {db,go}=useMember();
  const load=useLoad(()=>allRows<Entry>((from,to)=>db.from('journal_entries').select(journalColumns).order('created_at',{ascending:false}).order('id',{ascending:false}).range(from,to)),[db]);
  const exportEntries=()=>downloadText('well-vie-journal.txt',(load.data??[]).map(e=>`${dateLabel(e.created_at)}\n${e.title??''}\n${e.prompt_text??''}\n\n${e.body}`).join('\n\n________\n\n'));
  return <Page eyebrow="Private journal" title="A place for your own words" intro="These entries stay tied to your account and are not shared with other members." action={<button className="primary" onClick={()=>go('/write')}><PenLine size={18}/>Write</button>}>
    {load.loading?<Loading/>:load.error?<ErrorBox error={load.error} retry={load.reload}/>:<>
      <div className="actions journal-tools"><button className="outline" onClick={exportEntries}><Download size={18}/>Take a copy</button><button className="outline tonal" onClick={()=>go('/history')}><History size={18}/>Looking back</button></div>
      {!load.data?.length?<Empty title="Your journal begins here"><p>Write freely, or begin from a journal invitation inside The Reset.</p></Empty>:<div className="stack">{load.data.map(e=><button className="card entry-card" key={e.id} onClick={()=>go('/journal/'+e.id)}><h2>{cleanCopy(e.title)||'A quiet reflection'}</h2>{e.prompt_text&&<p className="muted">{cleanCopy(e.prompt_text)}</p>}<p className="line-clamp">{e.body}</p><small>{dateLabel(e.created_at)} · {timeLabel(e.created_at)}</small></button>)}</div>}
    </>}
  </Page>;
}
export function WriteJournal({query}:{query:string}){
  const {db,go}=useMember(),params=new URLSearchParams(query);
  const [prompt,setPrompt]=useState(params.get('prompt'));
  const practice=Number(params.get('practice'))||null;
  const returnTo=params.get('return')||'/journal';
  const [title,setTitle]=useState(''),[body,setBody]=useState('');
  const id=useRef(crypto.randomUUID()),saved=useRef(false),action=useAction();
  const prompts=useLoad(()=>result<{id:number;text:string}[]>(db.from('prompts').select('id,text').eq('active',true).order('id')),[db]);
  useEffect(()=>{if(!body&&!title)return;const unload=(e:BeforeUnloadEvent)=>{if(!saved.current){e.preventDefault();e.returnValue='';}};const navigate=(e:Event)=>{if(!saved.current&&!window.confirm('Leave this reflection without saving?'))e.preventDefault();};window.addEventListener('beforeunload',unload);window.addEventListener('wellvie-before-navigate',navigate);return()=>{window.removeEventListener('beforeunload',unload);window.removeEventListener('wellvie-before-navigate',navigate);};},[body,title]);
  return <section className="journal-write calm-enter"><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{if(!body.trim())throw new Error('Please enter a few words before saving.');await rpc(db,'create_journal_entry',{p_event_id:id.current,p_title:title.trim()||null,p_prompt_text:prompt||null,p_practice_id:practice,p_body:body.trim()});saved.current=true;go(returnTo);});}}>
    <div className="card journal-invitations">{prompt?<><h2>{cleanCopy(prompt)}</h2><button type="button" className="journal-change-prompt" onClick={()=>setPrompt(null)}>Choose a different journal invitation</button></>:<><h2>Or begin with a journal invitation</h2>{prompts.loading?<Loading/>:prompts.error?<ErrorBox error={prompts.error} retry={prompts.reload}/>:prompts.data?.map(p=><button type="button" key={p.id} className="outline tonal" onClick={()=>setPrompt(p.text)}><Quote size={18}/>{cleanCopy(p.text)}</button>)}</>}</div>
    <input aria-label="Title (optional)" placeholder="Title (optional)" maxLength={120} value={title} disabled={action.busy} onChange={e=>{id.current=crypto.randomUUID();setTitle(e.target.value);}}/>
    <textarea autoFocus aria-label="Journal entry" className="journal-editor" placeholder="Your words" required maxLength={20000} value={body} disabled={action.busy} onChange={e=>{id.current=crypto.randomUUID();setBody(e.target.value);}}/>
    {action.error&&<ErrorBox error={action.error}/>}<button className="primary full-width" disabled={action.busy||!body.trim()}>{action.busy?'Saving...':'Save privately'}</button>
  </form></section>;
}
export function JournalEntry({id}:{id:number}){const {db,go}=useMember();const load=useLoad(()=>result<Entry|null>(db.from('journal_entries').select(journalColumns).eq('id',id).maybeSingle()),[db,id]);const action=useAction();return <Page eyebrow={load.data?dateLabel(load.data.created_at):'Your journal'} title={load.data?.title||'A quiet reflection'} intro={load.data?.prompt_text??undefined} back={()=>go('/journal')}>{load.loading?<Loading/>:load.error?<ErrorBox error={load.error} retry={load.reload}/>:load.data?<><div className="card pre-wrap">{load.data.body}</div><button className="outline danger" disabled={action.busy} onClick={()=>{if(window.confirm('Delete this journal entry permanently? This cannot be undone.'))void action.run(async()=>{await result(db.from('journal_entries').delete().eq('id',id));go('/journal');});}}><Trash2 size={17}/>Let this entry go</button></>:<Empty title="This entry is no longer in your journal"/>}{action.error&&<ErrorBox error={action.error}/>}</Page>;}
export function ReflectionHistory(){const {db,go}=useMember();const load=useLoad(async()=>{const [intentions,checkins,entries]=await Promise.all([allRows<Intention>((a,b)=>db.from('intentions').select('id,text,created_at').order('created_at',{ascending:false}).order('id',{ascending:false}).range(a,b)),allRows<Checkin>((a,b)=>db.from('checkins').select('id,custom_feeling,created_at,feelings(label),needs(label)').order('created_at',{ascending:false}).order('id',{ascending:false}).range(a,b)),allRows<Entry>((a,b)=>db.from('journal_entries').select(journalColumns).order('created_at',{ascending:false}).order('id',{ascending:false}).range(a,b))]);return {intentions,checkins,entries};},[db]);const [text,setText]=useState('');const id=useRef(crypto.randomUUID());const action=useAction();return <Page eyebrow="Private reflections" title="Looking back" intro="A gentle record of how you have arrived, what you have written, and what you are carrying." back={()=>go('/journal')}><form className="card" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await rpc(db,'create_intention',{p_event_id:id.current,p_text:text.trim()});id.current=crypto.randomUUID();setText('');await load.reload();});}}><h2>An intention for this season</h2><textarea aria-label="New intention" maxLength={500} required value={text} onChange={e=>setText(e.target.value)} placeholder="What would you like to carry with you?"/><button className="primary" disabled={action.busy||!text.trim()}>Keep this intention</button>{action.error&&<ErrorBox error={action.error}/>}</form>{load.loading?<Loading/>:load.error?<ErrorBox error={load.error} retry={load.reload}/>:<><h2>Intentions</h2>{load.data?.intentions.map(i=><article className="card" key={i.id}><p className="pre-wrap">{i.text}</p><small>{dateLabel(i.created_at)}</small></article>)}<h2>Check-ins</h2>{load.data?.checkins.map(c=><article className="card" key={c.id}><h3>{c.custom_feeling||c.feelings?.label||'A moment to check in'}</h3><p>{c.needs?.label}</p><small>{dateLabel(c.created_at)}</small></article>)}{!load.data?.checkins.length&&!load.data?.intentions.length&&<Empty title="Every season starts here"/>}<button className="outline" onClick={()=>downloadText('well-vie-reflections.json',JSON.stringify(load.data,null,2),'application/json')}><Download size={18}/>Take a copy of all of it</button></>}</Page>;}
